package: v20240216
generate:
  models: true
output-options:
  skip-prune: true
import-mapping:
  ../common/common.yaml: github.com/snyk/code-client-go/internal/workspace/2024-03-12/common
output: scans/scans.go