// Code generated by MockGen. DO NOT EDIT.
// Source: upload_revision.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uploadrevision "github.com/snyk/code-client-go/internal/uploadrevision"
	scan "github.com/snyk/code-client-go/scan"
)

// MockUploadRevision is a mock of UploadRevision interface.
type MockUploadRevision struct {
	ctrl     *gomock.Controller
	recorder *MockUploadRevisionMockRecorder
}

// MockUploadRevisionMockRecorder is the mock recorder for MockUploadRevision.
type MockUploadRevisionMockRecorder struct {
	mock *MockUploadRevision
}

// NewMockUploadRevision creates a new mock instance.
func NewMockUploadRevision(ctrl *gomock.Controller) *MockUploadRevision {
	mock := &MockUploadRevision{ctrl: ctrl}
	mock.recorder = &MockUploadRevisionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadRevision) EXPECT() *MockUploadRevisionMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploadRevision) Upload(ctx context.Context, requestId string, target scan.Target, files <-chan string) (uploadrevision.RevisionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, requestId, target, files)
	ret0, _ := ret[0].(uploadrevision.RevisionID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUploadRevisionMockRecorder) Upload(ctx, requestId, target, files interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploadRevision)(nil).Upload), ctx, requestId, target, files)
}
