// Package v20241221 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v20241221

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID
