// Package v20240514 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package v20240514

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/snyk/code-client-go/internal/workspace/2024-05-14/common"
	externalRef1 "github.com/snyk/code-client-go/internal/workspace/2024-05-14/links"
)

// Defines values for WorkspacePostRequestDataAttributesWorkspaceType.
const (
	FileBundleWorkspace WorkspacePostRequestDataAttributesWorkspaceType = "file_bundle_workspace"
)

// Defines values for WorkspacePostRequestDataType.
const (
	WorkspacePostRequestDataTypeWorkspace WorkspacePostRequestDataType = "workspace"
)

// Defines values for WorkspacePostResponseDataType.
const (
	WorkspacePostResponseDataTypeWorkspace WorkspacePostResponseDataType = "workspace"
)

// WorkspacePostRequest defines model for WorkspacePostRequest.
type WorkspacePostRequest struct {
	Data struct {
		Attributes struct {
			// BundleId The bundle identifier
			BundleId string `json:"bundle_id"`

			// RepositoryUri The repository URI
			RepositoryUri string `json:"repository_uri"`

			// RootFolderId A consistent ID of the root folder path where the bundle was created (eg SHA-256 hash).
			RootFolderId string `json:"root_folder_id"`

			// WorkspaceType The type of workspace to create
			WorkspaceType WorkspacePostRequestDataAttributesWorkspaceType `json:"workspace_type"`
		} `json:"attributes"`
		Type WorkspacePostRequestDataType `json:"type"`
	} `json:"data"`
}

// WorkspacePostRequestDataAttributesWorkspaceType The type of workspace to create
type WorkspacePostRequestDataAttributesWorkspaceType string

// WorkspacePostRequestDataType defines model for WorkspacePostRequest.Data.Type.
type WorkspacePostRequestDataType string

// WorkspacePostResponse defines model for WorkspacePostResponse.
type WorkspacePostResponse struct {
	Data struct {
		// Id The workspace identifier
		Id openapi_types.UUID `json:"id"`

		// Type The REST resource
		Type WorkspacePostResponseDataType `json:"type"`
	} `json:"data"`
	Jsonapi *externalRef0.JsonApi  `json:"jsonapi,omitempty"`
	Links   *externalRef1.LinkSelf `json:"links,omitempty"`
}

// WorkspacePostResponseDataType The REST resource
type WorkspacePostResponseDataType string
