// Package v20250407 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package v20250407

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/snyk/code-client-go/internal/api/test/2025-04-07/common"
)

// Defines values for ComponentAttributesFindingsDocumentType.
const (
	Cyclonedx ComponentAttributesFindingsDocumentType = "cyclonedx"
	Sarif     ComponentAttributesFindingsDocumentType = "sarif"
)

// Defines values for GetComponentsResponseItemType.
const (
	Component GetComponentsResponseItemType = "component"
)

// ComponentAttributes defines model for ComponentAttributes.
type ComponentAttributes struct {
	// FindingsDocumentPath URL path for the findings document
	FindingsDocumentPath *string `json:"findings_document_path,omitempty"`

	// FindingsDocumentType Type of the findings document
	FindingsDocumentType *ComponentAttributesFindingsDocumentType `json:"findings_document_type,omitempty"`
	Id                   string                                   `json:"id"`
	Name                 *string                                  `json:"name,omitempty"`
	SeverityCounts       *SeverityCounts                          `json:"severity_counts,omitempty"`

	// Success Scan success status of the component
	Success bool `json:"success"`

	// Type Type of the component
	Type  string `json:"type"`
	Webui *WebUI `json:"webui,omitempty"`
}

// ComponentAttributesFindingsDocumentType Type of the findings document
type ComponentAttributesFindingsDocumentType string

// GetComponentsResponse defines model for GetComponentsResponse.
type GetComponentsResponse struct {
	Data    []GetComponentsResponseItem `json:"data"`
	Jsonapi externalRef0.JsonApi        `json:"jsonapi"`
	Links   struct {
		Next *externalRef0.LinkProperty `json:"next,omitempty"`
		Prev *externalRef0.LinkProperty `json:"prev,omitempty"`
		Self *externalRef0.LinkProperty `json:"self,omitempty"`
	} `json:"links"`
}

// GetComponentsResponseItem defines model for GetComponentsResponseItem.
type GetComponentsResponseItem struct {
	Attributes ComponentAttributes           `json:"attributes"`
	Id         string                        `json:"id"`
	Type       GetComponentsResponseItemType `json:"type"`
}

// GetComponentsResponseItemType defines model for GetComponentsResponseItem.Type.
type GetComponentsResponseItemType string

// SeverityCounts defines model for SeverityCounts.
type SeverityCounts struct {
	// Critical Number of critical severity findings
	Critical *int `json:"critical,omitempty"`

	// High Number of high severity findings
	High *int `json:"high,omitempty"`

	// Low Number of low severity findings
	Low *int `json:"low,omitempty"`

	// Medium Number of medium severity findings
	Medium *int `json:"medium,omitempty"`
}

// WebUI defines model for WebUI.
type WebUI struct {
	// Link Link to the asset created in the Snyk web UI for this component
	Link *string `json:"link,omitempty"`

	// ProjectId The ID of the created project in the Snyk web UI for this component
	ProjectId *openapi_types.UUID `json:"project_id,omitempty"`

	// SnapshotId The ID of the created snapshot in the Snyk web UI for this component
	SnapshotId *openapi_types.UUID `json:"snapshot_id,omitempty"`
}
