version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

executors:
  default:
    docker:
      - image: cimg/go:1.21.1

# Define the jobs we want to run for this project
jobs:
  lint-and-format:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run: make format
      - run: make generate
      - run:
          name: Run go mod tidy"
          command: go mod tidy
      - run:
          name: Check if there are any changes
          command: |
            git status --porcelain=v1 | tee /dev/stderr | wc -l | grep -qE '^ *0 *$$'
      - run: make lint
  unit_test:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run:
          name: Run unit tests
          command: make test
  smoke_test:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run:
          name: Run smoke tests
          command: make smoke-test
  contract_test:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run:
          name: Run smoke tests
          command: make contract-test
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build
          command: make build
  security-scans:
    executor: default
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled
# Orchestrate our job run sequence
workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: dx-local-alerts
      - security-scans:
          name: Security Scans
          context: code-client-go
      - lint-and-format:
          name: Lint & Format
          context: code-client-go
      - unit_test:
          name: Unit tests
          requires:
            - Lint & Format
      - smoke_test:
          name: Smoke tests
          context:
            - code-client-go-smoke-tests-token
          requires:
            - Unit tests
      - contract_test:
          name: Contract tests
          requires:
            - Unit tests
      - build:
          name: Build
          requires:
            - Smoke tests
            - Contract tests
            - Security Scans
            - Scan repository for secrets
