version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

executors:
  default:
    docker:
      - image: cimg/go:1.21.1

# Define the jobs we want to run for this project
jobs:
  lint-and-format:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run: make format
      - run:
          name: "Ensure go.mod is tidy"
          command: |
            go mod tidy
            git diff --exit-code go.mod go.sum
      - run: make lint
  unit_test:
    executor: default
    steps:
      - checkout
      - run:
          name: Install tools
          command: make tools
      - run:
          name: Run unit tests
          command: make test
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build
          command: make build
  security-scans:
    executor: default
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled
# Orchestrate our job run sequence
workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: dx-local-alerts
      - security-scans:
          name: Security Scans
          context: code-client-go
      - lint-and-format:
          name: Lint & Format
      - unit_test:
          name: Unit tests
          requires:
            - Lint & Format
      - build:
          name: Build
          requires:
            - Unit tests
            - Security Scans
            - Scan repository for secrets
