// Package v20240216 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package v20240216

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/snyk/code-client-go/internal/orchestration/2024-02-16/common"
	externalRef1 "github.com/snyk/code-client-go/internal/orchestration/2024-02-16/parameters"
	externalRef2 "github.com/snyk/code-client-go/internal/orchestration/2024-02-16/scans"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateScanWorkspaceJobInternalParams defines parameters for CreateScanWorkspaceJobInternal.
type CreateScanWorkspaceJobInternalParams struct {
	// Version The requested version of the endpoint to process the request
	Version externalRef0.Version `form:"version" json:"version"`
}

// GetScanWorkspaceJobInternalParams defines parameters for GetScanWorkspaceJobInternal.
type GetScanWorkspaceJobInternalParams struct {
	// Version The requested version of the endpoint to process the request
	Version externalRef0.Version `form:"version" json:"version"`
}

// CreateScanWorkspaceJobForUserParams defines parameters for CreateScanWorkspaceJobForUser.
type CreateScanWorkspaceJobForUserParams struct {
	// Version The requested version of the endpoint to process the request
	Version externalRef0.Version `form:"version" json:"version"`
}

// GetScanWorkspaceJobForUserParams defines parameters for GetScanWorkspaceJobForUser.
type GetScanWorkspaceJobForUserParams struct {
	// Version The requested version of the endpoint to process the request
	Version externalRef0.Version `form:"version" json:"version"`
}

// CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody defines body for CreateScanWorkspaceJobInternal for application/vnd.api+json ContentType.
type CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody = externalRef2.PostScanRequest

// CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody defines body for CreateScanWorkspaceJobForUser for application/vnd.api+json ContentType.
type CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody = externalRef2.PostScanRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateScanWorkspaceJobInternalWithBody request with any body
	CreateScanWorkspaceJobInternalWithBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateScanWorkspaceJobInternalWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, body CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScanWorkspaceJobInternal request
	GetScanWorkspaceJobInternal(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobInternalParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateScanWorkspaceJobForUserWithBody request with any body
	CreateScanWorkspaceJobForUserWithBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateScanWorkspaceJobForUserWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, body CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScanWorkspaceJobForUser request
	GetScanWorkspaceJobForUser(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobForUserParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateScanWorkspaceJobInternalWithBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScanWorkspaceJobInternalRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateScanWorkspaceJobInternalWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, body CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScanWorkspaceJobInternalRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScanWorkspaceJobInternal(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobInternalParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScanWorkspaceJobInternalRequest(c.Server, orgId, scanjobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateScanWorkspaceJobForUserWithBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScanWorkspaceJobForUserRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateScanWorkspaceJobForUserWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, body CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScanWorkspaceJobForUserRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScanWorkspaceJobForUser(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobForUserParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScanWorkspaceJobForUserRequest(c.Server, orgId, scanjobId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateScanWorkspaceJobInternalRequestWithApplicationVndAPIPlusJSONBody calls the generic CreateScanWorkspaceJobInternal builder with application/vnd.api+json body
func NewCreateScanWorkspaceJobInternalRequestWithApplicationVndAPIPlusJSONBody(server string, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, body CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateScanWorkspaceJobInternalRequestWithBody(server, orgId, params, "application/vnd.api+json", bodyReader)
}

// NewCreateScanWorkspaceJobInternalRequestWithBody generates requests for CreateScanWorkspaceJobInternal with any type of body
func NewCreateScanWorkspaceJobInternalRequestWithBody(server string, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/orgs/%s/scans", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetScanWorkspaceJobInternalRequest generates requests for GetScanWorkspaceJobInternal
func NewGetScanWorkspaceJobInternalRequest(server string, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobInternalParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "scanjob_id", runtime.ParamLocationPath, scanjobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/orgs/%s/scans/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateScanWorkspaceJobForUserRequestWithApplicationVndAPIPlusJSONBody calls the generic CreateScanWorkspaceJobForUser builder with application/vnd.api+json body
func NewCreateScanWorkspaceJobForUserRequestWithApplicationVndAPIPlusJSONBody(server string, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, body CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateScanWorkspaceJobForUserRequestWithBody(server, orgId, params, "application/vnd.api+json", bodyReader)
}

// NewCreateScanWorkspaceJobForUserRequestWithBody generates requests for CreateScanWorkspaceJobForUser with any type of body
func NewCreateScanWorkspaceJobForUserRequestWithBody(server string, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/scans", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetScanWorkspaceJobForUserRequest generates requests for GetScanWorkspaceJobForUser
func NewGetScanWorkspaceJobForUserRequest(server string, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobForUserParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "scanjob_id", runtime.ParamLocationPath, scanjobId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/scans/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateScanWorkspaceJobInternalWithBodyWithResponse request with any body
	CreateScanWorkspaceJobInternalWithBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobInternalResponse, error)

	CreateScanWorkspaceJobInternalWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, body CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobInternalResponse, error)

	// GetScanWorkspaceJobInternalWithResponse request
	GetScanWorkspaceJobInternalWithResponse(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobInternalParams, reqEditors ...RequestEditorFn) (*GetScanWorkspaceJobInternalResponse, error)

	// CreateScanWorkspaceJobForUserWithBodyWithResponse request with any body
	CreateScanWorkspaceJobForUserWithBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobForUserResponse, error)

	CreateScanWorkspaceJobForUserWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, body CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobForUserResponse, error)

	// GetScanWorkspaceJobForUserWithResponse request
	GetScanWorkspaceJobForUserWithResponse(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobForUserParams, reqEditors ...RequestEditorFn) (*GetScanWorkspaceJobForUserResponse, error)
}

type CreateScanWorkspaceJobInternalResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON201 *externalRef2.ScanResponse
	ApplicationvndApiJSON400 *externalRef0.N400
	ApplicationvndApiJSON401 *externalRef0.N401
	ApplicationvndApiJSON403 *externalRef0.N403
	ApplicationvndApiJSON404 *externalRef0.N404
	ApplicationvndApiJSON429 *externalRef0.ErrorDocument
	ApplicationvndApiJSON500 *externalRef0.N500
}

// Status returns HTTPResponse.Status
func (r CreateScanWorkspaceJobInternalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateScanWorkspaceJobInternalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScanWorkspaceJobInternalResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *externalRef2.ScanResultsResponse
	ApplicationvndApiJSON400 *externalRef0.N400
	ApplicationvndApiJSON401 *externalRef0.N401
	ApplicationvndApiJSON403 *externalRef0.N403
	ApplicationvndApiJSON404 *externalRef0.N404
	ApplicationvndApiJSON429 *externalRef0.ErrorDocument
	ApplicationvndApiJSON500 *externalRef0.N500
}

// Status returns HTTPResponse.Status
func (r GetScanWorkspaceJobInternalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScanWorkspaceJobInternalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateScanWorkspaceJobForUserResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON201 *externalRef2.ScanResponse
	ApplicationvndApiJSON400 *externalRef0.N400
	ApplicationvndApiJSON401 *externalRef0.N401
	ApplicationvndApiJSON403 *externalRef0.N403
	ApplicationvndApiJSON404 *externalRef0.N404
	ApplicationvndApiJSON429 *externalRef0.ErrorDocument
	ApplicationvndApiJSON500 *externalRef0.N500
}

// Status returns HTTPResponse.Status
func (r CreateScanWorkspaceJobForUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateScanWorkspaceJobForUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScanWorkspaceJobForUserResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *externalRef2.ScanResultsResponse
	ApplicationvndApiJSON400 *externalRef0.N400
	ApplicationvndApiJSON401 *externalRef0.N401
	ApplicationvndApiJSON403 *externalRef0.N403
	ApplicationvndApiJSON404 *externalRef0.N404
	ApplicationvndApiJSON429 *externalRef0.ErrorDocument
	ApplicationvndApiJSON500 *externalRef0.N500
}

// Status returns HTTPResponse.Status
func (r GetScanWorkspaceJobForUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScanWorkspaceJobForUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateScanWorkspaceJobInternalWithBodyWithResponse request with arbitrary body returning *CreateScanWorkspaceJobInternalResponse
func (c *ClientWithResponses) CreateScanWorkspaceJobInternalWithBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobInternalResponse, error) {
	rsp, err := c.CreateScanWorkspaceJobInternalWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScanWorkspaceJobInternalResponse(rsp)
}

func (c *ClientWithResponses) CreateScanWorkspaceJobInternalWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobInternalParams, body CreateScanWorkspaceJobInternalApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobInternalResponse, error) {
	rsp, err := c.CreateScanWorkspaceJobInternalWithApplicationVndAPIPlusJSONBody(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScanWorkspaceJobInternalResponse(rsp)
}

// GetScanWorkspaceJobInternalWithResponse request returning *GetScanWorkspaceJobInternalResponse
func (c *ClientWithResponses) GetScanWorkspaceJobInternalWithResponse(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobInternalParams, reqEditors ...RequestEditorFn) (*GetScanWorkspaceJobInternalResponse, error) {
	rsp, err := c.GetScanWorkspaceJobInternal(ctx, orgId, scanjobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScanWorkspaceJobInternalResponse(rsp)
}

// CreateScanWorkspaceJobForUserWithBodyWithResponse request with arbitrary body returning *CreateScanWorkspaceJobForUserResponse
func (c *ClientWithResponses) CreateScanWorkspaceJobForUserWithBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobForUserResponse, error) {
	rsp, err := c.CreateScanWorkspaceJobForUserWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScanWorkspaceJobForUserResponse(rsp)
}

func (c *ClientWithResponses) CreateScanWorkspaceJobForUserWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId externalRef1.OrgId, params *CreateScanWorkspaceJobForUserParams, body CreateScanWorkspaceJobForUserApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScanWorkspaceJobForUserResponse, error) {
	rsp, err := c.CreateScanWorkspaceJobForUserWithApplicationVndAPIPlusJSONBody(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScanWorkspaceJobForUserResponse(rsp)
}

// GetScanWorkspaceJobForUserWithResponse request returning *GetScanWorkspaceJobForUserResponse
func (c *ClientWithResponses) GetScanWorkspaceJobForUserWithResponse(ctx context.Context, orgId externalRef1.OrgId, scanjobId externalRef1.ScanJobId, params *GetScanWorkspaceJobForUserParams, reqEditors ...RequestEditorFn) (*GetScanWorkspaceJobForUserResponse, error) {
	rsp, err := c.GetScanWorkspaceJobForUser(ctx, orgId, scanjobId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScanWorkspaceJobForUserResponse(rsp)
}

// ParseCreateScanWorkspaceJobInternalResponse parses an HTTP response from a CreateScanWorkspaceJobInternalWithResponse call
func ParseCreateScanWorkspaceJobInternalResponse(rsp *http.Response) (*CreateScanWorkspaceJobInternalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateScanWorkspaceJobInternalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest externalRef2.ScanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest externalRef0.ErrorDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseGetScanWorkspaceJobInternalResponse parses an HTTP response from a GetScanWorkspaceJobInternalWithResponse call
func ParseGetScanWorkspaceJobInternalResponse(rsp *http.Response) (*GetScanWorkspaceJobInternalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScanWorkspaceJobInternalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef2.ScanResultsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest externalRef0.ErrorDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseCreateScanWorkspaceJobForUserResponse parses an HTTP response from a CreateScanWorkspaceJobForUserWithResponse call
func ParseCreateScanWorkspaceJobForUserResponse(rsp *http.Response) (*CreateScanWorkspaceJobForUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateScanWorkspaceJobForUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest externalRef2.ScanResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest externalRef0.ErrorDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}

// ParseGetScanWorkspaceJobForUserResponse parses an HTTP response from a GetScanWorkspaceJobForUserWithResponse call
func ParseGetScanWorkspaceJobForUserResponse(rsp *http.Response) (*GetScanWorkspaceJobForUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScanWorkspaceJobForUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef2.ScanResultsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest externalRef0.ErrorDocument
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}
