package: v20240216
generate:
  client: true
  models: true
output-options:
  skip-prune: true
import-mapping:
  ./common/common.yaml: github.com/snyk/code-client-go/internal/orchestration/2024-02-16/common
  ./parameters/orgs.yaml: github.com/snyk/code-client-go/internal/orchestration/2024-02-16/parameters
  ./parameters/scans.yaml: github.com/snyk/code-client-go/internal/orchestration/2024-02-16/parameters
  ./scans/scans.yaml: github.com/snyk/code-client-go/internal/orchestration/2024-02-16/scans
output: client.go