// Package v20240514 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package v20240514

// Link defines model for Link.
type Link struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`
}

// LinkSelf defines model for LinkSelf.
type LinkSelf struct {
	Self Link `json:"self"`
}
