// Package v20240312 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package v20240312

// Defines values for ContentTypeHeader.
const (
	ApplicationvndApiJson ContentTypeHeader = "application/vnd.api+json"
)

// ContentTypeHeader defines model for ContentTypeHeader.
type ContentTypeHeader string
