// Package v20240312 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package v20240312

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID
