// Package v20240312 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package v20240312

// UserAgent defines model for UserAgent.
type UserAgent = string
