// Package v20240216 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package v20240216

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// OrgId defines model for OrgId.
type OrgId = openapi_types.UUID
