// Package v20240216 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package v20240216

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ScanJobId defines model for ScanJobId.
type ScanJobId = openapi_types.UUID
