// Package v20240514 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package v20240514

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// RequestId defines model for RequestId.
type RequestId = openapi_types.UUID
