// Code generated by MockGen. DO NOT EDIT.
// Source: analysis.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	bundle "github.com/snyk/code-client-go/bundle"
	analysis "github.com/snyk/code-client-go/internal/analysis"
	sarif "github.com/snyk/code-client-go/sarif"
	scan "github.com/snyk/code-client-go/scan"
)

// MockAnalysisOrchestrator is a mock of AnalysisOrchestrator interface.
type MockAnalysisOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockAnalysisOrchestratorMockRecorder
}

// MockAnalysisOrchestratorMockRecorder is the mock recorder for MockAnalysisOrchestrator.
type MockAnalysisOrchestratorMockRecorder struct {
	mock *MockAnalysisOrchestrator
}

// NewMockAnalysisOrchestrator creates a new mock instance.
func NewMockAnalysisOrchestrator(ctrl *gomock.Controller) *MockAnalysisOrchestrator {
	mock := &MockAnalysisOrchestrator{ctrl: ctrl}
	mock.recorder = &MockAnalysisOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalysisOrchestrator) EXPECT() *MockAnalysisOrchestratorMockRecorder {
	return m.recorder
}

// RunLegacyTest mocks base method.
func (m *MockAnalysisOrchestrator) RunLegacyTest(ctx context.Context, bundleHash, shardKey string, limitToFiles []string, severity int) (*sarif.SarifResponse, scan.LegacyScanStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunLegacyTest", ctx, bundleHash, shardKey, limitToFiles, severity)
	ret0, _ := ret[0].(*sarif.SarifResponse)
	ret1, _ := ret[1].(scan.LegacyScanStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RunLegacyTest indicates an expected call of RunLegacyTest.
func (mr *MockAnalysisOrchestratorMockRecorder) RunLegacyTest(ctx, bundleHash, shardKey, limitToFiles, severity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunLegacyTest", reflect.TypeOf((*MockAnalysisOrchestrator)(nil).RunLegacyTest), ctx, bundleHash, shardKey, limitToFiles, severity)
}

// RunTest mocks base method.
func (m *MockAnalysisOrchestrator) RunTest(ctx context.Context, orgId string, b bundle.Bundle, target scan.Target, reportingOptions analysis.AnalysisConfig) (*sarif.SarifResponse, *scan.ResultMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTest", ctx, orgId, b, target, reportingOptions)
	ret0, _ := ret[0].(*sarif.SarifResponse)
	ret1, _ := ret[1].(*scan.ResultMetaData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RunTest indicates an expected call of RunTest.
func (mr *MockAnalysisOrchestratorMockRecorder) RunTest(ctx, orgId, b, target, reportingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTest", reflect.TypeOf((*MockAnalysisOrchestrator)(nil).RunTest), ctx, orgId, b, target, reportingOptions)
}

// RunTestRemote mocks base method.
func (m *MockAnalysisOrchestrator) RunTestRemote(ctx context.Context, orgId string, reportingOptions analysis.AnalysisConfig) (*sarif.SarifResponse, *scan.ResultMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTestRemote", ctx, orgId, reportingOptions)
	ret0, _ := ret[0].(*sarif.SarifResponse)
	ret1, _ := ret[1].(*scan.ResultMetaData)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RunTestRemote indicates an expected call of RunTestRemote.
func (mr *MockAnalysisOrchestratorMockRecorder) RunTestRemote(ctx, orgId, reportingOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTestRemote", reflect.TypeOf((*MockAnalysisOrchestrator)(nil).RunTestRemote), ctx, orgId, reportingOptions)
}
