// Package v20240312 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.4 DO NOT EDIT.
package v20240312

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	externalRef0 "github.com/snyk/code-client-go/internal/workspace/2024-03-12/common"
	externalRef1 "github.com/snyk/code-client-go/internal/workspace/2024-03-12/links"
)

// Defines values for WorkspacePostRequestDataAttributesWorkspaceType.
const (
	FileBundleWorkspace WorkspacePostRequestDataAttributesWorkspaceType = "file_bundle_workspace"
)

// Defines values for WorkspacePostRequestDataType.
const (
	WorkspacePostRequestDataTypeWorkspace WorkspacePostRequestDataType = "workspace"
)

// Defines values for WorkspacePostResponseDataType.
const (
	WorkspacePostResponseDataTypeWorkspace WorkspacePostResponseDataType = "workspace"
)

// WorkspacePostRequest defines model for WorkspacePostRequest.
type WorkspacePostRequest struct {
	Data struct {
		Attributes struct {
			BundleId      string                                          `json:"bundle_id"`
			RepositoryUri string                                          `json:"repository_uri"`
			WorkspaceType WorkspacePostRequestDataAttributesWorkspaceType `json:"workspace_type"`
		} `json:"attributes"`
		Type WorkspacePostRequestDataType `json:"type"`
	} `json:"data"`
}

// WorkspacePostRequestDataAttributesWorkspaceType defines model for WorkspacePostRequest.Data.Attributes.WorkspaceType.
type WorkspacePostRequestDataAttributesWorkspaceType string

// WorkspacePostRequestDataType defines model for WorkspacePostRequest.Data.Type.
type WorkspacePostRequestDataType string

// WorkspacePostResponse defines model for WorkspacePostResponse.
type WorkspacePostResponse struct {
	Data struct {
		Id   openapi_types.UUID            `json:"id"`
		Type WorkspacePostResponseDataType `json:"type"`
	} `json:"data"`
	Jsonapi *externalRef0.JsonApi  `json:"jsonapi,omitempty"`
	Links   *externalRef1.LinkSelf `json:"links,omitempty"`
}

// WorkspacePostResponseDataType defines model for WorkspacePostResponse.Data.Type.
type WorkspacePostResponseDataType string
